# HST Black NMC Configuration File
# Change number to run different cases (4, 8, 16, 32)
general {
    base_exp_dir = /content/drive/MyDrive/Tesi/neus/serious_analysis/runs/hst_black_nmc_32
    recording = [
        ./,
        ./models
    ]
}

dataset {
    data_dir = "/content/drive/MyDrive/Tesi/neus/serious_analysis/data/hst_black_nmc_32"
    # for training --> data_dir = ".../hst_black_nmc_32"
    # for validation --> data_dir = ".../hst_black_val_32"
    render_cameras_name = cameras_spe3r.npz
    object_cameras_name = cameras_spe3r.npz
}

train {
    learning_rate = 5e-4
    learning_rate_alpha = 0.05

    end_iter = 100000
    batch_size = 256
    warm_up_end = 100
    anneal_end = 0
    use_white_bkgd = False

    # robust to Colab crash + your milestone meshes
    save_freq = 5000
    val_freq = 5000
    val_mesh_freq = 25000
    report_freq = 100

    igr_weight = 0.1
    mask_weight = 0.1
    validate_resolution_level = 4
}

model {
    nerf {
        D = 8,
        d_in = 4,
        d_in_view = 3,
        W = 256,
        multires = 10,
        multires_view = 4,
        output_ch = 4,
        skips=[4],
        use_viewdirs=True
    }

    sdf_network {
        d_out = 257
        d_in = 3
        d_hidden = 256
        n_layers = 8
        skip_in = [4]
        multires = 6
        bias = 0.5
        scale = 1.0
        geometric_init = True
        weight_norm = True
    }

    variance_network { init_val = 0.3 }

    rendering_network {
        d_feature = 256
        mode = idr
        d_in = 9
        d_out = 3
        d_hidden = 256
        n_layers = 4
        weight_norm = True
        multires_view = 4
        squeeze_out = True
    }

    neus_renderer {
        n_samples = 32
        n_importance = 32
        n_outside = 0
        up_sample_steps = 2
        perturb = 1.0
    }
}
